name: Setup Rust
description: Install a Rust toolchain, initialize the cache, and optionally install cargo tools.
inputs:
  components:
    description: Comma-separated Rust components to install.
    required: false
    default: ""
  cargo-hack:
    description: Whether to install cargo-hack.
    required: false
    default: "false"
  cargo-nextest:
    description: Whether to install cargo-nextest.
    required: false
    default: "false"
  cargo-llvm-cov:
    description: Whether to install cargo-llvm-cov.
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
      with:
        toolchain: ${{ env.RUSTUP_TOOLCHAIN }}
        components: ${{ inputs.components }}
    - name: Initialize cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
    - name: Install cargo-hack
      if: ${{ inputs['cargo-hack'] == 'true' }}
      uses: taiki-e/install-action@16b05812d776ae1dfaabc8277e421fb6d2506419 # v2.82.7
      with:
        tool: cargo-hack
    - name: Install cargo-nextest
      if: ${{ inputs['cargo-nextest'] == 'true' }}
      uses: taiki-e/install-action@16b05812d776ae1dfaabc8277e421fb6d2506419 # v2.82.7
      with:
        tool: cargo-nextest
    - name: Install cargo-llvm-cov
      if: ${{ inputs['cargo-llvm-cov'] == 'true' }}
      uses: taiki-e/install-action@16b05812d776ae1dfaabc8277e421fb6d2506419 # v2.82.7
      with:
        tool: cargo-llvm-cov
