[settings]
idiomatic_version_file_enable_tools = ["rust"]

[tools]
"cargo:cargo-deny" = { version = "0.20.2", depends = "rust" }
"cargo:cargo-hack" = { version = "0.6.45", depends = "rust" }
"cargo:cargo-hakari" = { version = "0.9.38", depends = "rust" }
"cargo:cargo-llvm-cov" = { version = "0.8.7", depends = "rust" }
"cargo:cargo-nextest" = { version = "0.9.140", depends = "rust" }
"cargo:clippy-sarif" = { version = "0.8.0", depends = "rust" }
"cargo:sarif-fmt" = { version = "0.8.0", depends = "rust" }
# LINT.IfChange(committed_version)
committed = "1.1.11"
# LINT.ThenChange(
#     //.github/workflows/committed.yaml:committed_version,
#     //.pre-commit-config.yaml:committed_version,
# )
git-cliff = "2.13.1"
just = "1.56.0"
# LINT.IfChange(prek_version)
prek = "0.4.4"
# LINT.ThenChange(//.github/workflows/pre-commit.yaml:prek_version)
taplo = "0.10.0"
yamlfmt = "0.21.0"
