name: pre-commit
permissions:
  contents: read
on:
  pull_request:
  push:
    branches: [main]
env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1
  # LINT.IfChange(msrv)
  RUSTUP_TOOLCHAIN: "1.97.1"
  # LINT.ThenChange(//Cargo.toml:msrv)
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: prek
        uses: j178/prek-action@e98a699c41eb69ab013a45817a0406469a748f8d # v2.0.5
        with:
          # LINT.IfChange(prek_version)
          prek-version: "0.4.10"
          # LINT.ThenChange(//mise.toml:prek_version)
